### ISSUE TITLE
Implement (performance) tracking

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/backend#4]
- [x] time between connect and shadow delivered 
  - [x] healthCheck:receivingMessageDuration #25 
- [x] Message bridge health
  - [x] healthCheck:fail
  - [x] healthCheck:success
- [x] age of shadow at time of delivery
- [x] unrecognized device message 
- [x] daily active unique devices
- [x] daily active unique fingerprints
